### ISSUE TITLE
travis ci 빌드 시 "The request was rejected."

### ISSUE THREAD

**Issue by MDJuniooor** [ButFit/butfit-backend-daeseong.mun#1]
해당 repo가 private repo이고, organization 계정에서는 selected repo만 적용할 수 있는 걸로 보입니다.

**Comment by limdongkyu** [comment]
현재 repo 를 public 으로 변경하였습니다. 다시 한번 확인 부탁드립니다.

**Comment by MDJuniooor** [comment]
travis ci 에서는 repo가 퍼블릭으로 변경 적용이 안되네요. Git Action으로 진행하겠습니다~
